### PR TITLE
Tab completion

### PR DESCRIPTION
**Pull request by parrotlync**
Hey there. I don't know if it's OK to just create a pull request, so if not feel free to delete it. 
I thought it would be nice if MCJukebox had Tabcompletion in game so I added this. I changed the CommandExecutor to a TabExecutor and added the TabComplete method.

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hey @ParrotLync! This is awesome, thanks for taking the time to do it. It never harms to ask before opening a PR, but in this case, it's definitely something I wanted.

Do you think we could do more to generate the suggestions automatically? I'm imagining that the top level suggestions would come from `commands.keySet()`. For args, we could maybe have like a getSuggestions() method on `JukeboxCommand` that knows how to generate the suggestions for itself?

Final thing - might be nice to prioritise the command sender when doing a player argument?

**Comment by parrotlync** [comment]
Hi @oliverdunk! Automatically generating some suggestions is definitely a thing we could do! And prioritising the command sender is a very good idea. I'm going to look into it!

**Comment by parrotlync** [comment]
Hey Oliver. I quickly looked into it and it seems that prioritising the command sender isn't gonna work as Bukkit sorts the suggestions alphabetically (or there should be something that can override this). 

The automated suggestions however could work out. I'm planning on adding a `HashMap<Integer, List<Object>>` to the `JukeboxCommand`. In this map is an Integer for argument position (length) and a list of possible arguments. I've also created an enum `JukeboxArgument` with types `PLAYER` `SHOW` `REGION`. If these are detected in the `getSuggestion()` method the suggestions will be added.

Do you think this could work or would you have a simpler idea? Thanks!

**Comment by oliverdunk** [comment]
Thanks for continuing on so quickly!

> it seems that prioritising the command sender isn't gonna work as Bukkit sorts the suggestions alphabetically (or there should be something that can override this).

Ah, I wasn't aware of that. I've never played with the tab completion APIs so I'm willing to trust you.

> The automated suggestions however could work out. I'm planning on adding a `HashMap<Integer, List<Object>>` to the `JukeboxCommand`. In this map is an Integer for argument position (length) and a list of possible arguments. I've also created an enum `JukeboxArgument` with types `PLAYER` `SHOW` `REGION`. If these are detected in the `getSuggestion()` method the suggestions will be added.

Hmm. I see what you're trying to do, but the use of Object terrifies me. Could you maybe create an abstract TabArgument class? It would have a getSuggestions() method, and implementors would provide a list there. There would be a RegionTabArgument, StringTabArgument etc. They are probably all small enough to be implemented in the same class.

That way, getSuggestions in JukeboxCommand can just return a TabArgument[].

If you have any questions, happy to chat on Discord (Oliver#4333).

**Comment by parrotlync** [comment]
Hey @oliverdunk! Everything should work now as discussed! I've pushed everything for you to look over.
MCJ-TabSuggestion

**Comment by oliverdunk** [comment]
@ParrotLync I haven't forgotten about this one! Will try to review and test tomorrow.

**Comment by oliverdunk** [comment]
Thanks again for taking the time to work on this. I just tested everything, and it seems to work great. LGTM.

**Pull request merged**
