### PR TITLE
Update WG 7 RegionProvider

### PR DESCRIPTION
**Pull request by Geitenijs**

### CODE REVIEW

**Comment by oliverdunk** [comment]
Thanks for this! Would you be able to merge with `master` for me, so the Travis build completes? Also just a heads up that we might keep this on another branch until WorldGuard makes the snapshot a release.

**Comment by Geitenijs** [comment]
@oliverdunk Not sure how to do that, sorry. I'm kinda new to GitHub.

**Comment by oliverdunk** [comment]
No problem @Geitenijs. When I look into this, I can merge myself if needsbe.

Just a heads up - I really appreciate your PR, but I'm aware that one of our developers is about to open one, too. I'm going to compare both approaches and merge whichever seems best.

From what I've been told, it seems like yours might be slightly more verbose, as you're getting a Bukkit world and then converting it to a WorldGuard one. Apparently there's a way to get a WorldEdit world from the start.

**Comment by oliverdunk** [comment]
Closing for the reasons discussed. Thank you regardless for this - please don't hesitate to open PRs in the future.

**Pull request closed without merging**
