### PR TITLE
Better Spigot detection

### PR DESCRIPTION
**Pull request by Moutard3**
Change Spigot detection to avoid conflicts with other plugins (e.g.
ViaVersion)

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hi @Moutard3, thanks for putting this together. Do you know why the older string causes conflicts? I wouldn't mind merging this but don't really understand why it is any different.

**Comment by Moutard3** [comment]
I can't manage to find why your code isn't working while mine does...
To be honest, I just searched on Spigot Forums how to detect Spigot and I saw everyone using org.spigotmc.SpigotConfig so I tried it and it worked but actually I can't explain you why it's working :/
Plus, I'm not used to java so it's harder to understand that :'(

**Comment by njb-said** [comment]
Just an idea:
Could do both? - Try the first one if that fails then the second.
I have always used SpigotConfig to check for spigot, weird why TextComponent not working though.

**Comment by Moutard3** [comment]
I don't see how you want to do that, if one fail the other will fail too. The problem here is that it pass where it should fail.

**Comment by njb-said** [comment]
Well, as you say the method you use works, but as @oliverdunk says the one he uses works. So it could just be the individual environment, therefore doing both gives more chance of success.
There's no harm in having both anyway as far as I can see :stuck_out_tongue:

**Comment by Moutard3** [comment]
Yeah but the one he uses doesn't work in Craftbukkit. ofc you can use both, but the one he uses would throw fake positive so you would have to be careful on how you set it up :)

**Pull request merged**
