### PR TITLE
Added connected players method to API

### PR DESCRIPTION
**Pull request by njb-said**
This is a workaround so that plugins can see who has the audio client
open.
The API method is unmodifiable to avoid concurrency issues or conflicts.

It keeps track of connect and disconnect events and adds them to a set.
In the future it would be best to handle this from the backend audio
server and redis for persistence.

I also formatted everything using spaces instead of tabs for indents at a width of 4.
Before I did that some files were using tabs and others were using spaces, this makes it more uniform 👍

### CODE REVIEW

**Comment by oliverdunk** [comment]
Sorry for taking so long to get back to you on this one. I love the idea, but my thought is that we should do this server side before implementing anything into the API? I think that people might get confused with the half functionality of it only working if the user joined after the restart.

Open to any suggestions/input as I might be overthinking this.

**Comment by njb-said** [comment]
I understand what you mean, for 9/10 instances this would work fine, as doing reloads are discouraged and that's the only way the set would be emptied.

However, I think we should probably add something to the audio server regardless. Not sure how or when you want to do this though 😛

**Comment by njb-said** [comment]
Oh, oops. I didn't realise those changes would end up here, in this PR.

Maybe we could get the connected players feature done too? 😛 
(Or I could temporarily remove the connected players from the API, but wouldn't suit this PR title)

**Comment by oliverdunk** [comment]
With our new connected players system we could have JBS report a list of active players to MCJukebox at regular intervals. That could then be stored in a variable exposed by an API method. Closing this for now as I think that's a better approach - your tabs to spaces commit would be a nice one to have as a separate PR that we can merge.

**Pull request closed without merging**
