### PR TITLE
Fix onDisable errors

### PR DESCRIPTION
**Pull request by Phineas**

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hi, thanks for contributing. I'm not sure what error you're getting, but this fix doesn't seem to make sense because even if the file doesn't exist then surely we still want to create it?

**Comment by Phineas** [comment]
@oliverdunk People that don't use the WorldGuard feature will get this error on disable, like me;
http://phineas.pw/screenshots/0iwfn.png

**Comment by oliverdunk** [comment]
A better solution would be to change the load method in RegionUtils to load the file if it exists, or if not to just initialise a blank HashMap.

**Comment by Phineas** [comment]
Wouldn't this way be more efficient since HashMaps take space up in memory?

**Comment by oliverdunk** [comment]
Closing this as we're releasing the plugin 2.0 soon which should hopefully fix these issues. If you're still having them after, feel free to open it again.

**Pull request closed without merging**
