### PR TITLE
Add gitignore + fix library shading issues (relocation)

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by sgdc3** [comment]
Should fix library conflicts with other plugins.

**Comment by oliverdunk** [comment]
Hi there,

Thank you so much for the contribution!

The changes that you've made look good to me, but I noticed that the Travis build is failing. I'll need to take a look to see why this is before merging, and I'll try to do that for you as soon as I can.

**Comment by sgdc3** [comment]
Lol, it seems that travis doesn't like java 7

**Comment by Moutard3** [comment]
I think that you don't need the apt part with java 7 (see: https://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs)

**Comment by sgdc3** [comment]
@Moutard3 Then i think that the travis jdk7 evironment doesn't have the JAVA_HOME variable set.

**Comment by Moutard3** [comment]
It will as long as you keep `jdk: oraclejdk7`

EDIT: maybe you'll need to add the java_home var in the global env

**Comment by oliverdunk** [comment]
Hi there,

Have you got any thoughts on if you'll be able to fix the Travis build? This change has been requested a few times, and so I'd love to merge it if you get a chance :)

**Comment by oliverdunk** [comment]
The Travis issue was a Travis issue rather than one on your end. It has been fixed and I have taken the majority of your PR into our master branch.

Thanks so much for your help! Do feel free to make more PRs if you ever wish!

**Pull request closed without merging**
